service: congenial-palm-tree
frameworkVersion: 3

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

function:
  api:
    handler: index.handler
    events: 
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline